query proposalsCount ($docId: String!) {
  queryDao (filter: { docId: { eq: $docId }}) {
    docId
    proposalAggregate {
        count
    }
    votableAggregate {
      count
    }
    stagingpropAggregate {
      count
    }
  }
}
