query stageProposals($docId: String!, $first: Int!, $offset: Int!) {
  queryDao(filter: { docId: { eq: $docId } }) {
    details_daoName_n
    docId
    votable(first: $first, offset: $offset, order: { desc: createdDate }) {
      docId
      type

      ... on Poll {
        ballot_expiration_t
        details_title_s
        details_description_s
        details_state_s
        creator
        createdDate

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Budget {
        details_title_s
        details_description_s
        details_state_s
        circle {
          docId
        }
        details_pegAmount_a
        details_voiceAmount_a
        details_rewardAmount_a
        creator
        createdDate

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Questcomplet {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s
        details_state_s

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Queststart {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s
        details_state_s

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Policy {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s
        details_state_s

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Circle {
        details_dao_i
        details_state_s

        details_title_s
        details_description_s

        ballot_expiration_t
        creator
        createdDate

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Payout {
        details_dao_i
        details_state_s

        details_title_s
        details_description_s
        details_url_s

        details_usdAmount_a
        details_deferredPercX100_i

        details_pegAmount_a
        details_rewardAmount_a
        details_voiceAmount_a

        ballot_expiration_t
        creator
        createdDate
        details_owner_n
        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Assignment {
        creator
        createdDate

        ballot_expiration_t

        details_title_s
        details_description_s

        details_assignee_n
        details_periodCount_i
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        start {
          details_startTime_t
        }
        claimed {
          docId
        }

        details_pegSalaryPerPeriod_a
        details_rewardSalaryPerPeriod_a
        details_voiceSalaryPerPeriod_a

        details_timeShareX100_i
        details_deferredPercX100_i

        details_state_s
        role {
          ... on Role {
            type
            docId
            details_state_s
            details_title_s
            details_description_s
            details_annualUsdSalary_a
            details_minDeferredX100_i
            details_minTimeShareX100_i
          }
        }
        details_assignee_n
        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Assignbadge {
        details_description_s
        details_title_s
        ballot_expiration_t
        details_state_s
        details_periodCount_i
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        badge {
          details_icon_s
          details_pegCoefficientX10000_i
          details_voiceCoefficientX10000_i
          details_rewardCoefficientX10000_i
        }
        details_startPeriod_i
        details_assignee_n
        createdDate
        creator
        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Role {
        ballot_expiration_t
        details_title_s
        details_description_s
        details_annualUsdSalary_a
        details_minDeferredX100_i
        details_state_s
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_minTimeShareX100_i
        details_owner_n
        createdDate
        creator
        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Badge {
        creator
        createdDate

        ballot_expiration_t
        details_title_s
        details_description_s
        details_pegCoefficientX10000_i
        details_voiceCoefficientX10000_i
        details_rewardCoefficientX10000_i
        details_icon_s
        details_state_s
        details_maxCycles_i
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        vote {
          vote_voter_n
          vote_vote_s
        }
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
            creator
            createdDate
          }
        }
        system_proposer_n
        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Edit {
        details_dao_i
        details_state_s

        creator
        details_ballotTitle_s
        details_ballotDescription_s
        ballot_expiration_t
        details_assignee_n
        details_periodCount_i
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_timeShareX100_i
        details_deferredPercX100_i
        details_state_s
        createdDate
        original {
          __typename
          ... on Assignbadge {
            details_title_s
            details_description_s
            start {
              details_startTime_t
            }
            badge {
              details_title_s
            }
          }
          ... on Assignment {
            details_title_s
            details_description_s
            claimed {
              docId
            }
            start {
              details_startTime_t
            }
            details_pegSalaryPerPeriod_a
            details_rewardSalaryPerPeriod_a
            details_voiceSalaryPerPeriod_a
            role {
              ... on Role {
                details_title_s
                details_annualUsdSalary_a
                details_minDeferredX100_i
              }
            }
          }
        }

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }
    }
  }
}
