query proposalsCount ($docId: String!, $systemAccount: String!) {
  queryDao (filter: { docId: { eq: $docId }}) {
    docId
    proposalAggregate {
      count
    }
    votableAggregate {
      count
    }
    stagingpropAggregate {
      count
    }
    passedpropsAggregate(filter: {not: {creator: {eq: $systemAccount}}}) {
      count
    }
    failedpropsAggregate(filter: {not: {creator: {eq: $systemAccount}}}) {
      count
    }
  }
}
