subscription proposal($docId: String!) {
  getDocument(docId: $docId) {
    __typename
    docId
    creator
    createdDate

    ... on Badge {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Queststart {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Policy {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Payout {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Edit {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }
    ... on Assignment {
      details_usdSalaryValuePerPhase_a
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Assignbadge {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }

    ... on Role {
      cmntsect {
        docId
        comment {
          id: docId
          author: comment_author_n
          content: comment_content_s
          createdDate
          deletedStatus: comment_deleted_i

          reactions: reaction {
            reactionlnkrAggregate {
              count
            }

            reactionlnkr {
              author: details_member_n
            }
          }

          commentAggregate {
            count
          }
        }
      }
    }
  }
}
