query proposalCount ($daoId: String!, $initDate: DateTime!, $finalDate: DateTime!) {
  getDao (docId: $daoId) {
    docId
    proposalAggregate( filter: {
      createdDate: {
        between: {
          min: $initDate
          max: $finalDate
        }
      }
    }) {
      count
    }
  }
}
