query proposals($docId: String!, $user: String, $first: Int!, $offset: Int!) {
  queryDao(filter: { docId: { eq: $docId } }) {
    details_daoName_n
    docId
    proposal(first: $first, offset: $offset, order: { desc: createdDate }) {
      docId
      __typename

      ... on Budget {
        ballot_expiration_t
        details_title_s
        details_description_s
        details_state_s
        circle {
          docId
        }
        details_pegAmount_a
        details_voiceAmount_a
        details_rewardAmount_a
        creator
        createdDate

        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Queststart {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s

        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Questcomplet {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s

        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Policy {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s

        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Circle {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s

        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Payout {
        ballot_expiration_t

        creator
        createdDate

        details_title_s
        details_description_s

        details_pegAmount_a
        details_rewardAmount_a
        details_voiceAmount_a
        details_voiceAmount_a
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_owner_n

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Assignment {
        creator
        claimed {
          docId
        }
        ballot_expiration_t
        details_title_s
        details_description_s
        details_assignee_n
        details_periodCount_i
        start {
          details_startTime_t
        }
        details_pegSalaryPerPeriod_a
        details_rewardSalaryPerPeriod_a
        details_voiceSalaryPerPeriod_a
        details_timeShareX100_i
        lastimeshare {
          details_timeShareX100_i
        }
        details_deferredPercX100_i
        details_state_s
        role {
          ... on Role {
            details_title_s
            details_annualUsdSalary_a
            details_minDeferredX100_i
          }
        }
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_assignee_n

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Assignbadge {
        details_title_s
        details_description_s
        details_state_s
        details_badge_i
        creator
        createdDate
        ballot_expiration_t
        start {
          details_startTime_t
        }
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_assignee_n

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Role {
        details_title_s
        ballot_expiration_t
        details_annualUsdSalary_a
        details_title_s
        creator
        createdDate
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Badge {
        details_description_s
        details_title_s
        ballot_expiration_t
        creator
        createdDate
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        system_proposer_n

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }
      }

      ... on Suspend {
        details_description_s
        details_title_s
        ballot_expiration_t
        details_state_s
        creator
        createdDate
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
      }

      ... on Edit {
        creator
        details_ballotTitle_s
        details_ballotDescription_s
        ballot_expiration_t
        details_assignee_n
        details_periodCount_i
        details_ballotQuorum_i
        details_ballotSupply_a
        details_ballotAlignment_i
        details_timeShareX100_i
        details_deferredPercX100_i
        details_state_s

        cmntsect {
          docId
          comment {
            id: docId
            deletedStatus: comment_deleted_i
          }
        }

        original {
          __typename
          ... on Assignbadge {
            details_title_s
            details_description_s
            start {
              details_startTime_t
            }
            badge {
              details_title_s
            }
          }
          ... on Assignment {
            details_title_s
            details_description_s
            claimed {
              docId
            }
            start {
              details_startTime_t
            }
            details_pegSalaryPerPeriod_a
            details_rewardSalaryPerPeriod_a
            details_voiceSalaryPerPeriod_a
            role {
              ... on Role {
                details_title_s
                details_annualUsdSalary_a
                details_minDeferredX100_i
              }
            }
          }
        }
      }

      ... on Votable {
        pass: voteAggregate(filter: { vote_vote_s: { regexp: "/.*pass*./" } }) {
          count
        }
        abstain: voteAggregate(
          filter: { vote_vote_s: { regexp: "/.*abstain*./" } }
        ) {
          count
        }
        fail: voteAggregate(filter: { vote_vote_s: { regexp: "/.*fail*./" } }) {
          count
        }
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        vote(filter: { vote_voter_n: { eq: $user } }) {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
    }
  }
}
