query comment($docId: String!) {
  getComment(docId: $docId) {
    __typename
    id: docId
    author: comment_author_n
    content: comment_content_s
    createdDate

    reactions: reaction {
      reactionlnkrAggregate {
        count
      }

      reactionlnkr {
        author: details_member_n
      }
    }

    commentAggregate {
      count
    }

    replies: comment {
      id: docId
      author: comment_author_n
      content: comment_content_s
      createdDate

      reactions: reaction {
        reactionlnkrAggregate {
          count
        }

        reactionlnkr {
          author: details_member_n
        }
      }

      commentAggregate {
        count
      }
    }
  }
}
