query proposal ($docId: String!, $first: Int!, $offset: Int!) {
  getDocument (docId: $docId) {
    docId
    creator
    createdDate
    __typename
    ... on Payout {
      ballot_expiration_t
      details_title_s
      details_description_s
      details_rewardAmount_a
      details_pegAmount_a
      details_voiceAmount_a
      details_url_s
      details_state_s
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      voteAggregate {
        count
      }
      vote (
        first: $first
        offset: $offset
        order: {
          desc: createdDate
        }
      ) {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Assignment {
      claimed {
        docId
      }
      ballot_expiration_t
      details_title_s
      details_description_s
      details_assignee_n
      details_periodCount_i
      start {
        details_startTime_t
      }
      details_pegSalaryPerPeriod_a
      details_rewardSalaryPerPeriod_a
      details_voiceSalaryPerPeriod_a
      details_timeShareX100_i
      details_deferredPercX100_i
      details_state_s
      role {
        ... on Role {
          details_title_s
          details_annualUsdSalary_a
          details_minDeferredX100_i
        }
      }
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      voteAggregate {
        count
      }
      vote (
        first: $first
        offset: $offset
        order: {
          desc: createdDate
        }
      ) {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Role {
      ballot_expiration_t
      details_title_s
      details_description_s
      details_annualUsdSalary_a
      details_minDeferredX100_i
      details_state_s
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      voteAggregate {
        count
      }
      vote (
        first: $first
        offset: $offset
        order: {
          desc: createdDate
        }
      ) {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Badge{
      ballot_expiration_t
      details_title_s
      details_description_s
      details_pegCoefficientX10000_i
      details_voiceCoefficientX10000_i
      details_rewardCoefficientX10000_i
      details_icon_s
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      voteAggregate {
        count
      }
      vote (
        first: $first
        offset: $offset
        order: {
          desc: createdDate
        }
      ) {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
  }
}
