# add pagination
query proposals ($hash: String!, $after: DateTime!) {
  getDho (hash: $hash) {
    hash
    docId
    proposal (filter: { createdDate: { ge: $after } }, order: { desc: createdDate }) {
      hash
      docId
      creator
      createdDate
      __typename
      ... on Payout {
        details_title_s
        ballot_expiration_t
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        # This doesn't work because we can't filter on the interface
        # (filter: { vote_voter_n: { eq: "<username>" }})
        vote {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
      ... on Assignment {
        details_title_s
        ballot_expiration_t
        role {
          ... on Role {
            details_title_s
          }
        }
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        vote {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
      ... on Assignbadge {
        details_title_s
        ballot_expiration_t
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        vote {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
      ... on Edit {
        details_ballotTitle_s
        ballot_expiration_t
        original {
          ... on Assignment {
            details_title_s
            role {
              ... on Role {
                details_title_s
              }
            }
          }
        }
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        vote {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
      ... on Suspend {
        details_title_s
        ballot_expiration_t
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
          }
        }
        vote {
          ... on Vote {
            vote_date_t
            vote_voter_n
            vote_vote_s
            vote_votePower_a
          }
        }
      }
    }
  }
}
