query daoCircleList($daoId: Int64!) {
  queryCircle(
    filter: {
      details_autoApprove_i: { eq: 1 } 
      details_dao_i: { eq: $daoId }
    }
  ) {
    id: docId
    name: system_nodeLabel_s    
  }
}

