query getMemberVotes($username: String!, $first: Int, $offset: Int) {
  getMember(details_member_n: $username) {
    docId,
    __typename
    vote (first: $first, offset: $offset, order: { desc: createdDate}) {
      docId
      vote_vote_s
      vote_date_t
      voteon {
        creator
        docId
        __typename
        ... on Edit {
          details_title_s: details_ballotTitle_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Suspend {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Payout {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Role {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Assignbadge {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Assignment {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
        ... on Badge {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
       ... on Role {
          details_title_s
          dao {
            details_daoName_n
            settings {
              settings_daoTitle_s
            }
          }
        }
      }
    }
  }
}
