query queryActivity($username: String!, $daoId: String!, $first: Int, $offset: Int) {
  queryAssignment(filter:{details_assignee_n:{eq: $username}} first:$first, offset: $offset)@cascade(fields:["dao"]){
    details_title_s
    details_usdSalaryValuePerPhase_a
    details_state_s
    details_description_s
    details_startPeriod_c
    details_periodCount_i
    details_timeShareX100_i
    details_startPeriod_c_edge {
      details_label_s
      details_startTime_t
    }
    lastimeshare {
      details_timeShareX100_i
    }
    role {
      details_title_s
      details_state_s
      details_annualUsdSalary_a
      details_minDeferredX100_i
    }
    claimed {
      docId
    }
    details_approvedDeferredPercX100_i
    details_deferredPercX100_i
    docId
    dao(filter:{details_daoName_n:{eq:$daoId}}){
      details_daoName_n
    }
  }
}
