query profileDhos($username: String!, $first: Int, $offset: Int) {
  getMember(details_member_n: $username) {
    docId
    __typename
    createdDate
    details_member_n

    memberofAggregate {
      count
    }

    memberof(first: $first, offset: $offset) {
      ... on Dao {
        docId
        details_daoName_n
        settings {
          settings_daoTitle_s
          settings_isHypha_i
          settings_logo_s
          settings_daoUrl_s
        }
      }
    }

    applicantof {
      ... on Dao {
        details_daoName_n
        settings {
          settings_daoTitle_s
          settings_daoUrl_s
        }
      }
    }
  }
}
