query queryActivity($username: String!, $daoId: String!, $first: Int, $offset: Int) {
  getDao(docId: $daoId) {
    __typename
    votable(filter: {type: {in:["Assignment", "Assignbadge"]}, creator:{eq: $username} }, first:$first, offset: $offset, order: { desc: createdDate} ) {
      __typename
      ... on Assignment {
        type
        docId
        details_title_s
        details_usdSalaryValuePerPhase_a
        details_state_s
        details_description_s
        details_periodCount_i
        details_timeShareX100_i,
        details_ballotSupply_a
        details_ballotQuorum_i
        details_ballotAlignment_i
        details_pegSalaryPerPeriod_a
        details_rewardSalaryPerPeriod_a
        details_voiceSalaryPerPeriod_a
        start {
          details_startTime_t
          details_label_s
        }
        lastimeshare {
          details_timeShareX100_i
        }
        role {
          docId
          details_title_s
          details_description_s
          details_state_s
          details_annualUsdSalary_a
          details_minDeferredX100_i
          details_minTimeShareX100_i
        }
        claimed {
          docId
        }
        details_approvedDeferredPercX100_i
        details_deferredPercX100_i
        docId
        dao(filter:{details_daoName_n:{eq:$daoId}}){
          details_daoName_n
        }

      }
      ... on Assignbadge {
        type
        docId
        details_title_s
        details_description_s
        details_state_s
        details_badge_i
        creator
        createdDate
        details_periodCount_i
        details_ballotAlignment_i
        badge {
          docId
          details_title_s
          details_description_s
          details_state_s
          details_pegCoefficientX10000_i
          details_voiceCoefficientX10000_i
          details_rewardCoefficientX10000_i
        }
        start {
          details_startTime_t
        }

        dao(filter:{details_daoName_n:{eq:$daoId}}){
          details_daoName_n
        }
      }
      ... on Votable{
        ballot_expiration_t
        votetally {
          ... on VoteTally {
            pass_votePower_a
            fail_votePower_a
            abstain_votePower_a
            creator
            createdDate
          }
        }
        pass: voteAggregate (filter: {
          vote_vote_s: {
            regexp: "/.*pass*./"
          }
        }) {
          count
        }
        abstain: voteAggregate (filter: {
          vote_vote_s: {
            regexp: "/.*abstain*./"
          }
        }) {
          count
        }
        fail: voteAggregate (filter: {
          vote_vote_s: {
            regexp: "/.*fail*./"
          }
        }) {
          count
        }
      }
    }
  }
}
