query queryActivityContributions($username: String!, $daoId: String!, $first: Int, $offset: Int){
  queryPayout (filter:{details_recipient_n:{eq:$username}}, first: $first, offset: $offset, order: { desc: createdDate} ) @cascade(fields:["dao"]){
    docId,
    details_title_s,
    details_description_s,
    details_state_s,
    details_url_s,
    details_recipient_n,
    creator
    createdDate
    details_voiceAmount_a
    details_rewardAmount_a
    dao(filter:{docId:{eq:$daoId}}){
      details_daoName_n
    },
    votetally {
      ... on VoteTally {
        pass_votePower_a
        fail_votePower_a
        abstain_votePower_a
        creator
        createdDate
      }
    },
    ballot_expiration_t
    details_pegAmount_a
    details_ballotSupply_a
    details_ballotQuorum_i
    details_ballotAlignment_i
    pass: voteAggregate (filter: {
      vote_vote_s: {
        regexp: "/.*pass*./"
      }
    }) {
      count
    }
    abstain: voteAggregate (filter: {
      vote_vote_s: {
        regexp: "/.*abstain*./"
      }
    }) {
      count
    }
    fail: voteAggregate (filter: {
      vote_vote_s: {
        regexp: "/.*fail*./"
      }
    }) {
      count
    }
  }
}
