query getStats($username: String!, $daoId: Int64!, $daoName: String) {
  getDao(docId:$daoName) {
    docId
    votableAggregate(filter: {type: {in:["Assignment", "Assignbadge"]}, creator: {eq: $username}}){
      count
    }
  },
  getMember(details_member_n: $username) {
    payoutAggregate(filter: { details_dao_i: { eq: $daoId}}) {
      count
    }
  }
}
