query assignmentsPast ($username: String!) {
  queryMember(filter: { details_member_n: { eq: $username }}) {
    hash
    details_member_n
    assigned {
      hash
      __typename
      # Filtered by dho?
      ... on Assignment {
        details_title_s
        details_periodCount_i
        details_startPeriod_c_edge {
          details_startTime_t
        }
        details_state_s
        role {
          ... on Role {
            details_title_s
          }
        }
      }
    }
  }
}