query activeDao ($name: String!) {
  queryDao (filter: { details_daoName_n: { eq: $name }}) {
    hash
    docId
    details_daoName_n
    settings {
      settings_daoName_n
      settings_daoTitle_s
      settings_daoDescription_s
      settings_governanceTokenContract_n
      settings_pegToken_a
      settings_pegTokenContract_n
      settings_rewardToken_a
      settings_rewardTokenContract_n
      settings_rewardToPegRatio_a
      settings_treasuryContract_n
      settings_voiceToken_a
      settings_votingDurationSec_i
      settings_votingAlignmentX100_i
      settings_votingQuorumX100_i
      settings_usesSeeds_i
    }
    period {
      details_label_s
      details_startTime_t
      docId
      hash
    }
  }
}
