query dho {
  queryDho {
    settings {
      settings_pegToken_a
      settings_pegTokenContract_n
      settings_rewardTokenContract_n
      settings_governanceTokenContract_n
      settings_voiceToken_a
      settings_logo_s
      contract

      ecosystemPrice: settings_ecosystemPrice_a
      ecosystemPriceStaked: settings_ecosystemPriceStaked_a
      ecosystemChildPrice: settings_ecosystemChildPrice_a
      ecosystemChildPriceStaked: settings_ecosystemChildPriceStaked_a
    }
  }
}
