query periodsUpcoming($daoId: String, $after: DateTime!) {
  getDao(docId: $daoId) {
    details_daoName_n

    calendar {
      period(filter: { details_startTime_t: { ge: $after } }) {
        docId
        details_label_s
        details_startTime_t
      }
    }
  }
}
