# (hash: "bf48d76fe10595f9ffc90b9863ae92e02954396cededa5409993c43cc48c508d")
query profileDhos ($username: String!) {
  queryMember(filter: { details_member_n: { eq: $username }}) {
    hash
    createdDate
    details_member_n

    memberof {
      ... on Dao {
        hash
        details_daoName_n
        settings {
          settings_daoTitle_s
        }
      }
    }

    applicantof {
      ... on Dao {
        hash
        details_daoName_n
        settings {
          settings_daoTitle_s
        }
      }
    }
  }
}
