query profileDhos ($username: String!) {
  queryMember(filter: { details_member_n: { eq: $username }}) {
    hash
    createdDate
    details_member_n

    memberof {
      hash
      ... on Dho {
        details_rootNode_n
        system_nodeLabel_s

        settings {
          ... on Settings {
            hash
          }
        }
      }
    }
    applicantof {
      hash
      ... on Dho {
        details_rootNode_n
        system_nodeLabel_s
      }
    }

  }
}
