query proposal ($hash: String!) {
  getDocument (hash: $hash) {
    hash
    creator
    createdDate
    __typename
    ... on Payout {
      ballot_expiration_t
      details_title_s
      details_description_s
      details_usdAmount_a
      details_husdAmount_a
      details_hyphaAmount_a
      details_hvoiceAmount_a
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      vote {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Assignment {
      ballot_expiration_t
      details_title_s
      details_description_s
      details_url_s
      details_periodCount_i
      details_startPeriod_c_edge {
        details_startTime_t
      }
      details_husdSalaryPerPhase_a
      details_hvoiceSalaryPerPhase_a
      details_hyphaSalaryPerPhase_a
      details_state_s
      role {
        ... on Role {
          details_title_s
        }
      }
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      vote {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Assignbadge {
      ballot_expiration_t
      details_title_s
      details_description_s
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      vote {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
    ... on Suspend {
      ballot_expiration_t
      details_title_s
      details_description_s
      votetally {
        ... on VoteTally {
          pass_votePower_a
          fail_votePower_a
          abstain_votePower_a
        }
      }
      vote {
        ... on Vote {
         	vote_date_t
          vote_voter_n
          vote_vote_s
          vote_votePower_a
        }
      }
    }
  }
}
