query daoPolicyList($daoId: Int64!){
  queryPolicy(
    filter: {
      details_dao_i: { eq: $daoId }
      details_state_s: { regexp: "/approved/" } 
    } 
  ) {
    value: docId
    label: system_nodeLabel_s
  }
}