query daoTreasurers(
  $daoId: String!
  $first: Int
  $offset: Int
  $filter: MemberFilter
  $order: MemberOrder
) {
  getDao(docId: $daoId) {
    treasury {
      treasurer (first: $first, offset: $offset, filter: $filter, order: $order){
        docId
        details_requestor_n
      }
    }
  }
}