query daoList ($daoName: String, $first: Int!, $offset: Int!) {
  queryDao (
    order: {
      asc: details_daoName_n
    }
    filter: {
      details_daoName_n: {
        gt: $daoName
      }
    }
    first: $first
    offset: $offset
  ) {
    docId
    details_daoName_n
    createdDate
    memberAggregate {
      count
    }
    settings {
      settings_daoDescription_s 
    }
  }
}