query daoList($first: Int!, $offset: Int!) {
  queryDao (
    first: $first
    offset: $offset
  ) {
    docId
    details_daoName_n
    createdDate
    memberAggregate {
      count
    }
    settings {
      settings_daoDescription_s 
    }
  }
}