query daoBadges ($daoId: String!,  $first: Int, $offset: Int, $order: BadgeOrder, $filter: BadgeFilter) {
  getDao (docId: $daoId) {
    docId,
    details_daoName_n
    badge (first: $first, offset: $offset, order: $order, filter: $filter) {
      docId
      __typename
      assignment {
        docId
        details_assignee_n
        dao {
          details_daoName_n
        }
      }
      assignmentAggregate {
        count
      }
      ... on Badge {
        details_icon_s
        details_state_s
        details_title_s
        details_description_s
      }
    }
  }
}
