query getActiveAssignments ($daoId: String!) {
  getDao (docId: $daoId) {
    docId
    role @cascade(fields: ["assignment"]) {
      docId
      assignment (
        filter: {
          details_state_s: {
            regexp: "/.*approved.*/i"
          }
        }
      ) {
        docId
        creator
      }
    }
    badge @cascade(fields: ["assignment"]) {
      docId
      assignment (
        filter: {
          details_state_s: {
            regexp: "/.*approved.*/i"
          }
        }
      ) {
        docId
        creator
      }
    }
  }
}
