query PlanPage($daoId: String!) {
   plans: queryPricingPlan {
    id: docId
    name: details_name_s
    price: details_price_a
    maxMemberCount: details_maxMemberCount_i
    discountPerc: details_discountPercX10000_i
    eactivationPeriodSec: details_reactivationPeriodSec_i
    priceoffer {
      docId
    }
  }

  offers: queryPriceOffer {
    id: docId
    name: details_tag_s
    periodCount: details_periodCount_i
    discountPerc: details_discountPercX10000_i
  }

  getDao(docId: $daoId) {
    planmanager {
      bill {
        details_startDate_t
        details_expirationDate_t
        details_planName_s
        docId
        __typename
      }
      docId
      __typename
    }
    docId
    __typename
  }
}
