query daoQuestProgression($daoId: Int64!, $id: String!) {
  queryQueststart(filter: {docId: {eq: $id}, details_dao_i: {eq: $daoId}}) {
    docId
    details_state_s
    system_originalApprovedDate_t
    details_title_s
    updatedDate
  }
}