query activeAssignments ($daoId: Int64!, $initDate: DateTime!, $finalDate: DateTime!) {
  aggregateAssignment(
    filter:{ system_originalApprovedDate_t:{
      between : {
        min: $initDate
        max: $finalDate 
      }
    }
    details_dao_i: {
      eq: $daoId
    }
  }) {
    count
  }
}